### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by fabmm** [Y3Z0N/ImmersiveFX#13]
[09:21:07] [Worker-Main-4/ERROR] [DynamicSurroundings/Lib]: Unable to process asset excavated_variants:sounds.json (dynamic_asset_generator:client = excavated_variants:sounds.json)
java.io.IOException: Could not find resource in generated resources: excavated_variants:sounds.json
	at TRANSFORMER/dynamic_asset_generator@0.6.3/io.github.lukebemish.dynamic_asset_generator.forge.DynAssetGenClientResourcePack.m_8031_(DynAssetGenClientResourcePack.java:55)
	at TRANSFORMER/dsurround@5.0.0.4/dynamiclabs.immersivefx.lib.resource.ResourceAccessorPack.getAsset(ResourceAccessorPack.java:46)
	at TRANSFORMER/dsurround@5.0.0.4/dynamiclabs.immersivefx.lib.Singleton.get(Singleton.java:45)
	at TRANSFORMER/dsurround@5.0.0.4/dynamiclabs.immersivefx.lib.resource.ResourceAccessorBase.asBytes(ResourceAccessorBase.java:47)
	at TRANSFORMER/dsurround@5.0.0.4/dynamiclabs.immersivefx.lib.resource.IResourceAccessor.exists(IResourceAccessor.java:96)
	at TRANSFORMER/dsurround@5.0.0.4/dynamiclabs.immersivefx.lib.resource.ResourceUtils.findSounds(ResourceUtils.java:135)
	at TRANSFORMER/dsurround@5.0.0.4/dynamiclabs.immersivefx.sndctrl.library.SoundLibrary.initialize(SoundLibrary.java:82)
	at TRANSFORMER/dsurround@5.0.0.4/dynamiclabs.immersivefx.sndctrl.SoundControl.setupComplete(SoundControl.java:106)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18.2-40.1.35/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.35/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

[09:21:11] [Worker-Main-4/ERROR] [DynamicSurroundings/Lib]: Unable to process asset excavated_variants:acoustics.json (dynamic_asset_generator:client = excavated_variants:dsurround_configs/acoustics.json)
java.io.IOException: Could not find resource in generated resources: excavated_variants:dsurround_configs/acoustics.json
	at TRANSFORMER/dynamic_asset_generator@0.6.3/io.github.lukebemish.dynamic_asset_generator.forge.DynAssetGenClientResourcePack.m_8031_(DynAssetGenClientResourcePack.java:55)
	at TRANSFORMER/dsurround@5.0.0.4/dynamiclabs.immersivefx.lib.resource.ResourceAccessorPack.getAsset(ResourceAccessorPack.java:46)
	at TRANSFORMER/dsurround@5.0.0.4/dynamiclabs.immersivefx.lib.Singleton.get(Singleton.java:45)
	at TRANSFORMER/dsurround@5.0.0.4/dynamiclabs.immersivefx.lib.resource.ResourceAccessorBase.asBytes(ResourceAccessorBase.java:47)
	at TRANSFORMER/dsurround@5.0.0.4/dynamiclabs.immersivefx.lib.resource.IResourceAccessor.exists(IResourceAccessor.java:96)
	at TRANSFORMER/dsurround@5.0.0.4/dynamiclabs.immersivefx.lib.resource.ResourceUtils.findConfigs(ResourceUtils.java:90)
	at TRANSFORMER/dsurround@5.0.0.4/dynamiclabs.immersivefx.sndctrl.library.AcousticLibrary.initialize(AcousticLibrary.java:73)
	at TRANSFORMER/dsurround@5.0.0.4/dynamiclabs.immersivefx.sndctrl.SoundControl.setupComplete(SoundControl.java:107)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18.2-40.1.35/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.35/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by Y3Z0N** [comment]
Fixed

**Comment by fabmm** [comment]
Thank you! Is the update waiting for approval on curseforge?
